### ISSUE TITLE
Install have some error

### ISSUE THREAD

**Issue by Kingxudong** [bowang-lab/U-Mamba#1]
Install [Pytorch](https://pytorch.org/get-started/previous-versions/#linux-and-windows-4) 2.0.1: pip install torch==2.0.1 torchvision==0.15.2
Install [Mamba](https://github.com/state-spaces/mamba): pip install causal-conv1d==1.1.1 and pip install mamba-ssm

The torch version is 2.0.1, but the causal-conv1d==1.1.1 is for torch 1.12？

**Comment by JunMa11** [comment]
Hi @Kingxudong ,

Thanks for raising this issue. Could you please post the error here?

This is a complete list of our packages. `causal-conv1d==1.1.1`  works for `torch 2.0.1`. As an alternative, you can also use 
`causal-conv1d==1.0.1`.

```
$ pip list
Package                       Version      Editable project location
----------------------------- ------------ ----------------------------------
acvl-utils                    0.2
asttokens                     2.4.1
attrs                         23.2.0
Automat                       22.10.0
batchgenerators               0.25
buildtools                    1.0.6
causal-conv1d                 1.1.1
certifi                       2023.11.17
charset-normalizer            3.3.2
cmake                         3.28.1
comm                          0.2.1
connected-components-3d       3.12.4
constantly                    23.10.4
contourpy                     1.2.0
cycler                        0.12.1
debugpy                       1.8.0
decorator                     5.1.1
dicom2nifti                   2.4.9
docopt                        0.6.2
dynamic-network-architectures 0.2
einops                        0.7.0
exceptiongroup                1.2.0
executing                     2.0.1
filelock                      3.13.1
fonttools                     4.47.0
fsspec                        2023.12.2
furl                          2.1.3
future                        0.18.3
graphviz                      0.20.1
greenlet                      3.0.3
huggingface-hub               0.20.2
hyperlink                     21.0.0
idna                          3.6
imagecodecs                   2024.1.1
imageio                       2.33.1
incremental                   22.10.0
ipykernel                     6.28.0
ipython                       8.20.0
jedi                          0.19.1
Jinja2                        3.1.2
joblib                        1.3.2
jupyter_client                8.6.0
jupyter_core                  5.7.1
kiwisolver                    1.4.5
lazy_loader                   0.3
linecache2                    1.0.0
lit                           17.0.6
mamba-ssm                     1.1.1
MarkupSafe                    2.1.3
matplotlib                    3.8.2
matplotlib-inline             0.1.6
MedPy                         0.4.0
monai                         1.3.0
mpmath                        1.3.0
nest-asyncio                  1.5.8
networkx                      3.2.1
nibabel                       5.2.0
ninja                         1.11.1.1
nnunetv2                      2.1.1        /home/jma/Documents/U-Mamba/umamba
numpy                         1.26.3
nvidia-cublas-cu11            11.10.3.66
nvidia-cuda-cupti-cu11        11.7.101
nvidia-cuda-nvrtc-cu11        11.7.99
nvidia-cuda-runtime-cu11      11.7.99
nvidia-cudnn-cu11             8.5.0.96
nvidia-cufft-cu11             10.9.0.58
nvidia-curand-cu11            10.2.10.91
nvidia-cusolver-cu11          11.4.0.1
nvidia-cusparse-cu11          11.7.4.91
nvidia-nccl-cu11              2.14.3
nvidia-nvtx-cu11              11.7.91
opencv-python                 4.9.0.80
orderedmultidict              1.0.1
packaging                     23.2
pandas                        2.1.4
parso                         0.8.3
pexpect                       4.9.0
pillow                        10.2.0
pip                           23.3.1
platformdirs                  4.1.0
prompt-toolkit                3.0.43
psutil                        5.9.7
ptyprocess                    0.7.0
pure-eval                     0.2.2
pydicom                       2.4.4
Pygments                      2.17.2
pyparsing                     3.1.1
python-dateutil               2.8.2
python-gdcm                   3.0.22
pytz                          2023.3.post1
PyYAML                        6.0.1
pyzmq                         25.1.2
redo                          2.0.4
regex                         2023.12.25
requests                      2.31.0
safetensors                   0.4.1
scikit-image                  0.22.0
scikit-learn                  1.3.2
scipy                         1.11.4
seaborn                       0.13.1
setuptools                    68.2.2
SimpleITK                     2.3.1
simplejson                    3.19.2
six                           1.16.0
SQLAlchemy                    2.0.25
stack-data                    0.6.3
sympy                         1.12
threadpoolctl                 3.2.0
tifffile                      2023.12.9
tokenizers                    0.15.0
torch                         2.0.1
torchvision                   0.15.2
tornado                       6.4
tqdm                          4.66.1
traceback2                    1.4.0
traitlets                     5.14.1
transformers                  4.36.2
triton                        2.0.0
Twisted                       23.10.0
typing_extensions             4.9.0
tzdata                        2023.4
unittest2                     1.1.0
urllib3                       2.1.0
wcwidth                       0.2.13
wheel                         0.41.2
yacs                          0.1.8
zope.interface                6.1

```

**Comment by baoyi-A** [comment]
I have the same error here.
(umamba) C:\Users\admin>pip install causal-conv1d==1.0.1
Looking in indexes: https://pypi.mirrors.ustc.edu.cn/simple
Collecting causal-conv1d==1.0.1
  Downloading https://mirrors.bfsu.edu.cn/pypi/web/packages/ff/82/8696a3694d26737dc974b76aa5697cb9a84902617037aac7bdb98e7d3843/causal_conv1d-1.0.1.tar.gz (6.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\admin\AppData\Local\Temp\pip-install-74j6hcor\causal-conv1d_58da3f7123db4250be3583bb30bf4976\setup.py", line 9, in <module>
          from packaging.version import parse, Version
      ModuleNotFoundError: No module named 'packaging'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by JunMa11** [comment]
Hi @baoyi-A ,

It seems that you are using Windows rather than Linux. Unfortunately, we didn't have a Windows workstation to test it. could you please try to install it under Linux?

**Comment by w12l3-c** [comment]
I tried it in WSL2 ubuntu an it has the same error as @baoyi-A 
This error happened for both causal_conv1d and mamba-ssm

```
Collecting causal-conv1d==1.0.1
  Downloading causal_conv1d-1.0.1.tar.gz (6.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-_wv9g8gl/causal-conv1d_26bf68c6da4d4c859ac356fb2876c82a/setup.py", line 9, in <module>
          from packaging.version import parse, Version
      ModuleNotFoundError: No module named 'packaging'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by JunMa11** [comment]
Hi, we cannot figure out the reason with the limited context you posted. 

Since the error is related to the original mamba package, could you please post the issue here as well?

https://github.com/state-spaces/mamba

**Comment by w12l3-c** [comment]
sorry i just followed the steps in the README.md  and when I went to step 3 `pip install casual_conv1d` and `pip install mamba-ssm` it gave me the error I mentioned above, the snippet above is the error it displayed

**Comment by claycrews2002** [comment]
I had this same issue, `pip install packaging` solved it for me.
