### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by Franktanshuai** [bowang-lab/U-Mamba#64]
Traceback (most recent call last):
  File "/data/miniconda/envs/umamba/bin/nnUNetv2_train", line 33, in <module>
    sys.exit(load_entry_point('nnunetv2', 'console_scripts', 'nnUNetv2_train')())
  File "/data/coding/U-Mamba/umamba/nnunetv2/run/run_training.py", line 268, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/data/coding/U-Mamba/umamba/nnunetv2/run/run_training.py", line 204, in run_training
    nnunet_trainer.run_training()
  File "/data/coding/U-Mamba/umamba/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1250, in run_training
    self.on_train_start()
  File "/data/coding/U-Mamba/umamba/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 832, in on_train_start
    self.dataloader_train, self.dataloader_val = self.get_dataloaders()
  File "/data/coding/U-Mamba/umamba/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 627, in get_dataloaders
    dl_tr, dl_val = self.get_plain_dataloaders(initial_patch_size, dim)
  File "/data/coding/U-Mamba/umamba/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 647, in get_plain_dataloaders
    dl_tr = nnUNetDataLoader2D(dataset_tr, self.batch_size,
  File "/data/coding/U-Mamba/umamba/nnunetv2/training/dataloading/base_data_loader.py", line 38, in __init__
    self.data_shape, self.seg_shape = self.determine_shapes()
  File "/data/coding/U-Mamba/umamba/nnunetv2/training/dataloading/base_data_loader.py", line 57, in determine_shapes
    data, seg, properties = self._data.load_case(self.indices[0])
  File "/data/coding/U-Mamba/umamba/nnunetv2/training/dataloading/nnunet_dataset.py", line 81, in load_case
    entry = self[key]
  File "/data/coding/U-Mamba/umamba/nnunetv2/training/dataloading/nnunet_dataset.py", line 62, in __getitem__
    ret['properties'] = load_pickle(ret['properties_file'])
  File "/data/miniconda/envs/umamba/lib/python3.10/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 93, in load_pickle
    a = pickle.load(f)
ModuleNotFoundError: No module named 'numpy._core'

did anyone met this problem？

**Comment by yese12** [comment]
这不是缺numpy模块嘛，安装下就好了

**Comment by fuyuao000** [comment]
numpy._core is used in numpy 2.0 and above. If you are using torch 2.0, which is required by umamba, you should use numpy 1.x, such as the relatively stable version 1.24.3.
